# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: json_db.proto

require 'google/protobuf'

require 'sfapi_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sfapi.v1.DB" do
    repeated :films, :message, 1, "sfapi.v1.Film"
    repeated :people, :message, 2, "sfapi.v1.Person"
    repeated :planets, :message, 3, "sfapi.v1.Planet"
    repeated :species, :message, 4, "sfapi.v1.Species"
    repeated :starships, :message, 5, "sfapi.v1.Starship"
    repeated :vehicles, :message, 6, "sfapi.v1.Vehicle"
  end
end

module Sfapi
  module V1
    DB = Google::Protobuf::DescriptorPool.generated_pool.lookup("sfapi.v1.DB").msgclass
  end
end
