# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/database.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "practical.grpc.v1.SearchRequest" do
    optional :term, :string, 1
    optional :max_results, :int64, 2
  end
  add_message "practical.grpc.v1.SearchResponse" do
    optional :matched_term, :string, 1
    optional :content, :string, 2
    optional :rank, :int32, 3
  end
end

module Practical
  module Grpc
    module V1
      SearchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("practical.grpc.v1.SearchRequest").msgclass
      SearchResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("practical.grpc.v1.SearchResponse").msgclass
    end
  end
end
