// Code generated by mockery v1.0.0
package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import proto "github.com/backstopmedia/gRPC-book-example/server/proto"

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// GetFilmByID provides a mock function with given fields: ctx, id
func (_m *Provider) GetFilmByID(ctx context.Context, id string) (*proto.Film, error) {
	ret := _m.Called(ctx, id)

	var r0 *proto.Film
	if rf, ok := ret.Get(0).(func(context.Context, string) *proto.Film); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Film)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFilms provides a mock function with given fields: ctx
func (_m *Provider) GetFilms(ctx context.Context) ([]*proto.Film, error) {
	ret := _m.Called(ctx)

	var r0 []*proto.Film
	if rf, ok := ret.Get(0).(func(context.Context) []*proto.Film); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.Film)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
