// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thing.proto

/*
Package practical_grpc_v1 is a generated protocol buffer package.

It is generated from these files:
	thing.proto

It has these top-level messages:
	Thing
	ThingNotFoundError
	UpdateThingRequest
	UpdateThingResponse
*/
package practical_grpc_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Thing struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cool bool   `protobuf:"varint,3,opt,name=cool" json:"cool,omitempty"`
}

func (m *Thing) Reset()                    { *m = Thing{} }
func (m *Thing) String() string            { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()               {}
func (*Thing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Thing) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetCool() bool {
	if m != nil {
		return m.Cool
	}
	return false
}

type ThingNotFoundError struct {
	RequestedId int64  `protobuf:"varint,1,opt,name=requested_id,json=requestedId" json:"requested_id,omitempty"`
	Reason      string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (m *ThingNotFoundError) Reset()                    { *m = ThingNotFoundError{} }
func (m *ThingNotFoundError) String() string            { return proto.CompactTextString(m) }
func (*ThingNotFoundError) ProtoMessage()               {}
func (*ThingNotFoundError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ThingNotFoundError) GetRequestedId() int64 {
	if m != nil {
		return m.RequestedId
	}
	return 0
}

func (m *ThingNotFoundError) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type UpdateThingRequest struct {
	Thing *Thing `protobuf:"bytes,1,opt,name=thing" json:"thing,omitempty"`
	// allow callers to specify which fields should be updated
	Mask *google_protobuf.FieldMask `protobuf:"bytes,2,opt,name=mask" json:"mask,omitempty"`
}

func (m *UpdateThingRequest) Reset()                    { *m = UpdateThingRequest{} }
func (m *UpdateThingRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateThingRequest) ProtoMessage()               {}
func (*UpdateThingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateThingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

func (m *UpdateThingRequest) GetMask() *google_protobuf.FieldMask {
	if m != nil {
		return m.Mask
	}
	return nil
}

type UpdateThingResponse struct {
	Thing *Thing `protobuf:"bytes,1,opt,name=thing" json:"thing,omitempty"`
}

func (m *UpdateThingResponse) Reset()                    { *m = UpdateThingResponse{} }
func (m *UpdateThingResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateThingResponse) ProtoMessage()               {}
func (*UpdateThingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateThingResponse) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

func init() {
	proto.RegisterType((*Thing)(nil), "practical.grpc.v1.Thing")
	proto.RegisterType((*ThingNotFoundError)(nil), "practical.grpc.v1.ThingNotFoundError")
	proto.RegisterType((*UpdateThingRequest)(nil), "practical.grpc.v1.UpdateThingRequest")
	proto.RegisterType((*UpdateThingResponse)(nil), "practical.grpc.v1.UpdateThingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyService service

type MyServiceClient interface {
	UpdateThing(ctx context.Context, in *UpdateThingRequest, opts ...grpc.CallOption) (*UpdateThingResponse, error)
}

type myServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyServiceClient(cc *grpc.ClientConn) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) UpdateThing(ctx context.Context, in *UpdateThingRequest, opts ...grpc.CallOption) (*UpdateThingResponse, error) {
	out := new(UpdateThingResponse)
	err := grpc.Invoke(ctx, "/practical.grpc.v1.MyService/UpdateThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyService service

type MyServiceServer interface {
	UpdateThing(context.Context, *UpdateThingRequest) (*UpdateThingResponse, error)
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_UpdateThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).UpdateThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/practical.grpc.v1.MyService/UpdateThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).UpdateThing(ctx, req.(*UpdateThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "practical.grpc.v1.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateThing",
			Handler:    _MyService_UpdateThing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thing.proto",
}

func init() { proto.RegisterFile("thing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xdf, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xe9, 0x7e, 0xf1, 0xdd, 0xed, 0x17, 0xc1, 0x2b, 0x48, 0xd9, 0x53, 0x2d, 0x28, 0x7d,
	0xca, 0xb0, 0xfe, 0x01, 0x3e, 0x6d, 0xe0, 0xc3, 0x14, 0xaa, 0xbe, 0x09, 0x23, 0x6b, 0xb2, 0x1a,
	0xd6, 0xf5, 0xd6, 0x24, 0x1d, 0xf8, 0xdf, 0x4b, 0x93, 0x39, 0x94, 0x09, 0xe2, 0xdb, 0xcd, 0xe5,
	0xdc, 0xcf, 0xc9, 0x39, 0x10, 0xda, 0x57, 0x55, 0x97, 0xac, 0xd1, 0x64, 0x09, 0x4f, 0x1b, 0xcd,
	0x0b, 0xab, 0x0a, 0x5e, 0xb1, 0x52, 0x37, 0x05, 0xdb, 0x5d, 0x4f, 0xe2, 0x92, 0xa8, 0xac, 0xe4,
	0xd4, 0x09, 0x56, 0xed, 0x7a, 0xba, 0x56, 0xb2, 0x12, 0xcb, 0x2d, 0x37, 0x1b, 0x7f, 0x94, 0xdc,
	0xc2, 0xf0, 0xa9, 0x63, 0xe0, 0x09, 0xf4, 0x94, 0x88, 0x82, 0x38, 0x48, 0xfb, 0x79, 0x4f, 0x09,
	0x44, 0x18, 0xd4, 0x7c, 0x2b, 0xa3, 0x5e, 0x1c, 0xa4, 0xe3, 0xdc, 0xcd, 0xdd, 0xae, 0x20, 0xaa,
	0xa2, 0x7e, 0x1c, 0xa4, 0xff, 0x72, 0x37, 0x27, 0x0f, 0x80, 0x0e, 0x70, 0x4f, 0x76, 0x4e, 0x6d,
	0x2d, 0x66, 0x5a, 0x93, 0xc6, 0x0b, 0xf8, 0xaf, 0xe5, 0x5b, 0x2b, 0x8d, 0x95, 0x62, 0x79, 0xe0,
	0x86, 0x87, 0xdd, 0x9d, 0xc0, 0x73, 0x18, 0x69, 0xc9, 0x0d, 0xd5, 0x7b, 0x8b, 0xfd, 0x2b, 0xb1,
	0x80, 0xcf, 0x8d, 0xe0, 0x56, 0x3a, 0x6c, 0xee, 0x2f, 0x90, 0xc1, 0xd0, 0x65, 0x75, 0xa4, 0x30,
	0x8b, 0xd8, 0x51, 0x58, 0xe6, 0xf5, 0x5e, 0x86, 0x0c, 0x06, 0x5d, 0x4a, 0xc7, 0x0e, 0xb3, 0x09,
	0xf3, 0x45, 0xb0, 0xcf, 0x22, 0xd8, 0xbc, 0x2b, 0x62, 0xc1, 0xcd, 0x26, 0x77, 0xba, 0x64, 0x06,
	0x67, 0xdf, 0x5c, 0x4d, 0x43, 0xb5, 0x91, 0x7f, 0xb5, 0xcd, 0x14, 0x8c, 0x17, 0xef, 0x8f, 0x52,
	0xef, 0x54, 0x21, 0xf1, 0x05, 0xc2, 0x2f, 0x4c, 0xbc, 0xfc, 0xe1, 0xf8, 0x38, 0xe9, 0xe4, 0xea,
	0x37, 0x99, 0xff, 0xda, 0x6a, 0xe4, 0xb2, 0xdc, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x47,
	0xc8, 0x16, 0x04, 0x02, 0x00, 0x00,
}
