# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sfapi.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GetFilmRequest" do
    optional :id, :string, 1
  end
  add_message "GetFilmResponse" do
    optional :film, :message, 1, "Film"
  end
  add_message "ListFilmsRequest" do
  end
  add_message "ListFilmsResponse" do
    repeated :films, :message, 1, "Film"
  end
  add_message "Film" do
    optional :id, :string, 1
    optional :title, :string, 2
    optional :director, :string, 3
    optional :producer, :string, 4
    optional :release_date, :message, 5, "google.protobuf.Timestamp"
  end
end

GetFilmRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetFilmRequest").msgclass
GetFilmResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetFilmResponse").msgclass
ListFilmsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ListFilmsRequest").msgclass
ListFilmsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ListFilmsResponse").msgclass
Film = Google::Protobuf::DescriptorPool.generated_pool.lookup("Film").msgclass
