// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swapi.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StarshipAction_Action int32

const (
	StarshipAction_TOOKOFF           StarshipAction_Action = 0
	StarshipAction_LANDED            StarshipAction_Action = 1
	StarshipAction_HYPERDRIVE        StarshipAction_Action = 2
	StarshipAction_HIDING_IN_A_MOUTH StarshipAction_Action = 3
)

var StarshipAction_Action_name = map[int32]string{
	0: "TOOKOFF",
	1: "LANDED",
	2: "HYPERDRIVE",
	3: "HIDING_IN_A_MOUTH",
}
var StarshipAction_Action_value = map[string]int32{
	"TOOKOFF":           0,
	"LANDED":            1,
	"HYPERDRIVE":        2,
	"HIDING_IN_A_MOUTH": 3,
}

func (x StarshipAction_Action) String() string {
	return proto1.EnumName(StarshipAction_Action_name, int32(x))
}
func (StarshipAction_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{31, 0} }

type Film struct {
	Title        string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	EpisodeId    int32    `protobuf:"varint,2,opt,name=episode_id,json=episodeId" json:"episode_id,omitempty"`
	OpeningCrawl string   `protobuf:"bytes,3,opt,name=opening_crawl,json=openingCrawl" json:"opening_crawl,omitempty"`
	Director     string   `protobuf:"bytes,4,opt,name=director" json:"director,omitempty"`
	Producer     string   `protobuf:"bytes,5,opt,name=producer" json:"producer,omitempty"`
	ReleaseDate  string   `protobuf:"bytes,6,opt,name=release_date,json=releaseDate" json:"release_date,omitempty"`
	Characters   []string `protobuf:"bytes,7,rep,name=characters" json:"characters,omitempty"`
	Planets      []string `protobuf:"bytes,8,rep,name=planets" json:"planets,omitempty"`
	Starships    []string `protobuf:"bytes,9,rep,name=starships" json:"starships,omitempty"`
	Vehicles     []string `protobuf:"bytes,10,rep,name=vehicles" json:"vehicles,omitempty"`
	Species      []string `protobuf:"bytes,11,rep,name=species" json:"species,omitempty"`
	Id           string   `protobuf:"bytes,12,opt,name=id" json:"id,omitempty"`
}

func (m *Film) Reset()                    { *m = Film{} }
func (m *Film) String() string            { return proto1.CompactTextString(m) }
func (*Film) ProtoMessage()               {}
func (*Film) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Film) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Film) GetEpisodeId() int32 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

func (m *Film) GetOpeningCrawl() string {
	if m != nil {
		return m.OpeningCrawl
	}
	return ""
}

func (m *Film) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *Film) GetProducer() string {
	if m != nil {
		return m.Producer
	}
	return ""
}

func (m *Film) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

func (m *Film) GetCharacters() []string {
	if m != nil {
		return m.Characters
	}
	return nil
}

func (m *Film) GetPlanets() []string {
	if m != nil {
		return m.Planets
	}
	return nil
}

func (m *Film) GetStarships() []string {
	if m != nil {
		return m.Starships
	}
	return nil
}

func (m *Film) GetVehicles() []string {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

func (m *Film) GetSpecies() []string {
	if m != nil {
		return m.Species
	}
	return nil
}

func (m *Film) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFilmRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetFilmRequest) Reset()                    { *m = GetFilmRequest{} }
func (m *GetFilmRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetFilmRequest) ProtoMessage()               {}
func (*GetFilmRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetFilmRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFilmResponse struct {
	Film *Film `protobuf:"bytes,1,opt,name=film" json:"film,omitempty"`
}

func (m *GetFilmResponse) Reset()                    { *m = GetFilmResponse{} }
func (m *GetFilmResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetFilmResponse) ProtoMessage()               {}
func (*GetFilmResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetFilmResponse) GetFilm() *Film {
	if m != nil {
		return m.Film
	}
	return nil
}

type ListFilmsRequest struct {
}

func (m *ListFilmsRequest) Reset()                    { *m = ListFilmsRequest{} }
func (m *ListFilmsRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListFilmsRequest) ProtoMessage()               {}
func (*ListFilmsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type ListFilmsResponse struct {
	Films []*Film `protobuf:"bytes,1,rep,name=films" json:"films,omitempty"`
}

func (m *ListFilmsResponse) Reset()                    { *m = ListFilmsResponse{} }
func (m *ListFilmsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListFilmsResponse) ProtoMessage()               {}
func (*ListFilmsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ListFilmsResponse) GetFilms() []*Film {
	if m != nil {
		return m.Films
	}
	return nil
}

type Vehicle struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model" json:"model,omitempty"`
	Manufacturer         string   `protobuf:"bytes,3,opt,name=manufacturer" json:"manufacturer,omitempty"`
	CostInCredits        int32    `protobuf:"varint,4,opt,name=cost_in_credits,json=costInCredits" json:"cost_in_credits,omitempty"`
	Length               float32  `protobuf:"fixed32,5,opt,name=length" json:"length,omitempty"`
	MaxAtmospheringSpeed int32    `protobuf:"varint,6,opt,name=max_atmosphering_speed,json=maxAtmospheringSpeed" json:"max_atmosphering_speed,omitempty"`
	Crew                 int32    `protobuf:"varint,7,opt,name=crew" json:"crew,omitempty"`
	Passengers           int32    `protobuf:"varint,8,opt,name=passengers" json:"passengers,omitempty"`
	CargoCapacity        int32    `protobuf:"varint,9,opt,name=cargo_capacity,json=cargoCapacity" json:"cargo_capacity,omitempty"`
	Consumables          string   `protobuf:"bytes,10,opt,name=consumables" json:"consumables,omitempty"`
	VehicleClass         string   `protobuf:"bytes,11,opt,name=vehicle_class,json=vehicleClass" json:"vehicle_class,omitempty"`
	Pilots               []string `protobuf:"bytes,12,rep,name=pilots" json:"pilots,omitempty"`
	Films                []string `protobuf:"bytes,13,rep,name=films" json:"films,omitempty"`
	Id                   string   `protobuf:"bytes,14,opt,name=id" json:"id,omitempty"`
}

func (m *Vehicle) Reset()                    { *m = Vehicle{} }
func (m *Vehicle) String() string            { return proto1.CompactTextString(m) }
func (*Vehicle) ProtoMessage()               {}
func (*Vehicle) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Vehicle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vehicle) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Vehicle) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Vehicle) GetCostInCredits() int32 {
	if m != nil {
		return m.CostInCredits
	}
	return 0
}

func (m *Vehicle) GetLength() float32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Vehicle) GetMaxAtmospheringSpeed() int32 {
	if m != nil {
		return m.MaxAtmospheringSpeed
	}
	return 0
}

func (m *Vehicle) GetCrew() int32 {
	if m != nil {
		return m.Crew
	}
	return 0
}

func (m *Vehicle) GetPassengers() int32 {
	if m != nil {
		return m.Passengers
	}
	return 0
}

func (m *Vehicle) GetCargoCapacity() int32 {
	if m != nil {
		return m.CargoCapacity
	}
	return 0
}

func (m *Vehicle) GetConsumables() string {
	if m != nil {
		return m.Consumables
	}
	return ""
}

func (m *Vehicle) GetVehicleClass() string {
	if m != nil {
		return m.VehicleClass
	}
	return ""
}

func (m *Vehicle) GetPilots() []string {
	if m != nil {
		return m.Pilots
	}
	return nil
}

func (m *Vehicle) GetFilms() []string {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Vehicle) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetVehicleRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetVehicleRequest) Reset()                    { *m = GetVehicleRequest{} }
func (m *GetVehicleRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetVehicleRequest) ProtoMessage()               {}
func (*GetVehicleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetVehicleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetVehicleResponse struct {
	Vehicle *Vehicle `protobuf:"bytes,1,opt,name=vehicle" json:"vehicle,omitempty"`
}

func (m *GetVehicleResponse) Reset()                    { *m = GetVehicleResponse{} }
func (m *GetVehicleResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetVehicleResponse) ProtoMessage()               {}
func (*GetVehicleResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *GetVehicleResponse) GetVehicle() *Vehicle {
	if m != nil {
		return m.Vehicle
	}
	return nil
}

type ListVehiclesRequest struct {
}

func (m *ListVehiclesRequest) Reset()                    { *m = ListVehiclesRequest{} }
func (m *ListVehiclesRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListVehiclesRequest) ProtoMessage()               {}
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type ListVehiclesResponse struct {
	Vehicles []*Vehicle `protobuf:"bytes,1,rep,name=vehicles" json:"vehicles,omitempty"`
}

func (m *ListVehiclesResponse) Reset()                    { *m = ListVehiclesResponse{} }
func (m *ListVehiclesResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListVehiclesResponse) ProtoMessage()               {}
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

type Starship struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model" json:"model,omitempty"`
	Manufacturer         string   `protobuf:"bytes,3,opt,name=manufacturer" json:"manufacturer,omitempty"`
	CostInCredits        int64    `protobuf:"varint,4,opt,name=cost_in_credits,json=costInCredits" json:"cost_in_credits,omitempty"`
	Length               float32  `protobuf:"fixed32,5,opt,name=length" json:"length,omitempty"`
	Crew                 int32    `protobuf:"varint,6,opt,name=crew" json:"crew,omitempty"`
	Passengers           int32    `protobuf:"varint,7,opt,name=passengers" json:"passengers,omitempty"`
	CargoCapacity        int64    `protobuf:"varint,8,opt,name=cargo_capacity,json=cargoCapacity" json:"cargo_capacity,omitempty"`
	Consumables          string   `protobuf:"bytes,9,opt,name=consumables" json:"consumables,omitempty"`
	HyperdriveRating     float32  `protobuf:"fixed32,10,opt,name=hyperdrive_rating,json=hyperdriveRating" json:"hyperdrive_rating,omitempty"`
	Mglt                 int32    `protobuf:"varint,11,opt,name=mglt" json:"mglt,omitempty"`
	StarshipClass        string   `protobuf:"bytes,12,opt,name=starship_class,json=starshipClass" json:"starship_class,omitempty"`
	Pilots               []string `protobuf:"bytes,13,rep,name=pilots" json:"pilots,omitempty"`
	Films                []string `protobuf:"bytes,14,rep,name=films" json:"films,omitempty"`
	Id                   string   `protobuf:"bytes,15,opt,name=id" json:"id,omitempty"`
	MaxAtmospheringSpeed int64    `protobuf:"varint,16,opt,name=max_atmosphering_speed,json=maxAtmospheringSpeed" json:"max_atmosphering_speed,omitempty"`
}

func (m *Starship) Reset()                    { *m = Starship{} }
func (m *Starship) String() string            { return proto1.CompactTextString(m) }
func (*Starship) ProtoMessage()               {}
func (*Starship) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *Starship) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Starship) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Starship) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Starship) GetCostInCredits() int64 {
	if m != nil {
		return m.CostInCredits
	}
	return 0
}

func (m *Starship) GetLength() float32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Starship) GetCrew() int32 {
	if m != nil {
		return m.Crew
	}
	return 0
}

func (m *Starship) GetPassengers() int32 {
	if m != nil {
		return m.Passengers
	}
	return 0
}

func (m *Starship) GetCargoCapacity() int64 {
	if m != nil {
		return m.CargoCapacity
	}
	return 0
}

func (m *Starship) GetConsumables() string {
	if m != nil {
		return m.Consumables
	}
	return ""
}

func (m *Starship) GetHyperdriveRating() float32 {
	if m != nil {
		return m.HyperdriveRating
	}
	return 0
}

func (m *Starship) GetMglt() int32 {
	if m != nil {
		return m.Mglt
	}
	return 0
}

func (m *Starship) GetStarshipClass() string {
	if m != nil {
		return m.StarshipClass
	}
	return ""
}

func (m *Starship) GetPilots() []string {
	if m != nil {
		return m.Pilots
	}
	return nil
}

func (m *Starship) GetFilms() []string {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Starship) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Starship) GetMaxAtmospheringSpeed() int64 {
	if m != nil {
		return m.MaxAtmospheringSpeed
	}
	return 0
}

type GetStarshipRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetStarshipRequest) Reset()                    { *m = GetStarshipRequest{} }
func (m *GetStarshipRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetStarshipRequest) ProtoMessage()               {}
func (*GetStarshipRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *GetStarshipRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetStarshipResponse struct {
	Starship *Starship `protobuf:"bytes,1,opt,name=starship" json:"starship,omitempty"`
}

func (m *GetStarshipResponse) Reset()                    { *m = GetStarshipResponse{} }
func (m *GetStarshipResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetStarshipResponse) ProtoMessage()               {}
func (*GetStarshipResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *GetStarshipResponse) GetStarship() *Starship {
	if m != nil {
		return m.Starship
	}
	return nil
}

type ListStarshipsRequest struct {
}

func (m *ListStarshipsRequest) Reset()                    { *m = ListStarshipsRequest{} }
func (m *ListStarshipsRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListStarshipsRequest) ProtoMessage()               {}
func (*ListStarshipsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type ListStarshipsResponse struct {
	Starships []*Starship `protobuf:"bytes,1,rep,name=starships" json:"starships,omitempty"`
}

func (m *ListStarshipsResponse) Reset()                    { *m = ListStarshipsResponse{} }
func (m *ListStarshipsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListStarshipsResponse) ProtoMessage()               {}
func (*ListStarshipsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *ListStarshipsResponse) GetStarships() []*Starship {
	if m != nil {
		return m.Starships
	}
	return nil
}

type Species struct {
	Name            string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Classification  string   `protobuf:"bytes,2,opt,name=classification" json:"classification,omitempty"`
	Designation     string   `protobuf:"bytes,3,opt,name=designation" json:"designation,omitempty"`
	AverageHeight   int32    `protobuf:"varint,4,opt,name=average_height,json=averageHeight" json:"average_height,omitempty"`
	SkinColors      string   `protobuf:"bytes,5,opt,name=skin_colors,json=skinColors" json:"skin_colors,omitempty"`
	EyeColors       string   `protobuf:"bytes,6,opt,name=eye_colors,json=eyeColors" json:"eye_colors,omitempty"`
	AverageLifespan int32    `protobuf:"varint,7,opt,name=average_lifespan,json=averageLifespan" json:"average_lifespan,omitempty"`
	Homeworld       string   `protobuf:"bytes,8,opt,name=homeworld" json:"homeworld,omitempty"`
	Language        string   `protobuf:"bytes,9,opt,name=language" json:"language,omitempty"`
	People          []string `protobuf:"bytes,10,rep,name=people" json:"people,omitempty"`
	Films           []string `protobuf:"bytes,11,rep,name=films" json:"films,omitempty"`
	Id              string   `protobuf:"bytes,12,opt,name=id" json:"id,omitempty"`
	HairColors      string   `protobuf:"bytes,13,opt,name=hair_colors,json=hairColors" json:"hair_colors,omitempty"`
}

func (m *Species) Reset()                    { *m = Species{} }
func (m *Species) String() string            { return proto1.CompactTextString(m) }
func (*Species) ProtoMessage()               {}
func (*Species) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *Species) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Species) GetClassification() string {
	if m != nil {
		return m.Classification
	}
	return ""
}

func (m *Species) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *Species) GetAverageHeight() int32 {
	if m != nil {
		return m.AverageHeight
	}
	return 0
}

func (m *Species) GetSkinColors() string {
	if m != nil {
		return m.SkinColors
	}
	return ""
}

func (m *Species) GetEyeColors() string {
	if m != nil {
		return m.EyeColors
	}
	return ""
}

func (m *Species) GetAverageLifespan() int32 {
	if m != nil {
		return m.AverageLifespan
	}
	return 0
}

func (m *Species) GetHomeworld() string {
	if m != nil {
		return m.Homeworld
	}
	return ""
}

func (m *Species) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Species) GetPeople() []string {
	if m != nil {
		return m.People
	}
	return nil
}

func (m *Species) GetFilms() []string {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Species) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Species) GetHairColors() string {
	if m != nil {
		return m.HairColors
	}
	return ""
}

type GetSpeciesRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetSpeciesRequest) Reset()                    { *m = GetSpeciesRequest{} }
func (m *GetSpeciesRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetSpeciesRequest) ProtoMessage()               {}
func (*GetSpeciesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *GetSpeciesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetSpeciesResponse struct {
	Species *Species `protobuf:"bytes,1,opt,name=species" json:"species,omitempty"`
}

func (m *GetSpeciesResponse) Reset()                    { *m = GetSpeciesResponse{} }
func (m *GetSpeciesResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetSpeciesResponse) ProtoMessage()               {}
func (*GetSpeciesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *GetSpeciesResponse) GetSpecies() *Species {
	if m != nil {
		return m.Species
	}
	return nil
}

type ListSpeciesRequest struct {
}

func (m *ListSpeciesRequest) Reset()                    { *m = ListSpeciesRequest{} }
func (m *ListSpeciesRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListSpeciesRequest) ProtoMessage()               {}
func (*ListSpeciesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

type ListSpeciesResponse struct {
	Species []*Species `protobuf:"bytes,1,rep,name=species" json:"species,omitempty"`
}

func (m *ListSpeciesResponse) Reset()                    { *m = ListSpeciesResponse{} }
func (m *ListSpeciesResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListSpeciesResponse) ProtoMessage()               {}
func (*ListSpeciesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *ListSpeciesResponse) GetSpecies() []*Species {
	if m != nil {
		return m.Species
	}
	return nil
}

type Planet struct {
	Name           string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RotationPeriod int32    `protobuf:"varint,2,opt,name=rotation_period,json=rotationPeriod" json:"rotation_period,omitempty"`
	OrbitalPeriod  int32    `protobuf:"varint,3,opt,name=orbital_period,json=orbitalPeriod" json:"orbital_period,omitempty"`
	Diameter       int32    `protobuf:"varint,4,opt,name=diameter" json:"diameter,omitempty"`
	Climate        string   `protobuf:"bytes,5,opt,name=climate" json:"climate,omitempty"`
	Gravity        float32  `protobuf:"fixed32,6,opt,name=gravity" json:"gravity,omitempty"`
	Terrain        string   `protobuf:"bytes,7,opt,name=terrain" json:"terrain,omitempty"`
	SurfaceWater   float32  `protobuf:"fixed32,8,opt,name=surface_water,json=surfaceWater" json:"surface_water,omitempty"`
	Population     int64    `protobuf:"varint,9,opt,name=population" json:"population,omitempty"`
	Residents      []string `protobuf:"bytes,10,rep,name=residents" json:"residents,omitempty"`
	Films          []string `protobuf:"bytes,11,rep,name=films" json:"films,omitempty"`
	Id             string   `protobuf:"bytes,12,opt,name=id" json:"id,omitempty"`
}

func (m *Planet) Reset()                    { *m = Planet{} }
func (m *Planet) String() string            { return proto1.CompactTextString(m) }
func (*Planet) ProtoMessage()               {}
func (*Planet) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *Planet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Planet) GetRotationPeriod() int32 {
	if m != nil {
		return m.RotationPeriod
	}
	return 0
}

func (m *Planet) GetOrbitalPeriod() int32 {
	if m != nil {
		return m.OrbitalPeriod
	}
	return 0
}

func (m *Planet) GetDiameter() int32 {
	if m != nil {
		return m.Diameter
	}
	return 0
}

func (m *Planet) GetClimate() string {
	if m != nil {
		return m.Climate
	}
	return ""
}

func (m *Planet) GetGravity() float32 {
	if m != nil {
		return m.Gravity
	}
	return 0
}

func (m *Planet) GetTerrain() string {
	if m != nil {
		return m.Terrain
	}
	return ""
}

func (m *Planet) GetSurfaceWater() float32 {
	if m != nil {
		return m.SurfaceWater
	}
	return 0
}

func (m *Planet) GetPopulation() int64 {
	if m != nil {
		return m.Population
	}
	return 0
}

func (m *Planet) GetResidents() []string {
	if m != nil {
		return m.Residents
	}
	return nil
}

func (m *Planet) GetFilms() []string {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Planet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPlanetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetPlanetRequest) Reset()                    { *m = GetPlanetRequest{} }
func (m *GetPlanetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetPlanetRequest) ProtoMessage()               {}
func (*GetPlanetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *GetPlanetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPlanetResponse struct {
	Planet *Planet `protobuf:"bytes,1,opt,name=planet" json:"planet,omitempty"`
}

func (m *GetPlanetResponse) Reset()                    { *m = GetPlanetResponse{} }
func (m *GetPlanetResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetPlanetResponse) ProtoMessage()               {}
func (*GetPlanetResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *GetPlanetResponse) GetPlanet() *Planet {
	if m != nil {
		return m.Planet
	}
	return nil
}

type ListPlanetsRequest struct {
}

func (m *ListPlanetsRequest) Reset()                    { *m = ListPlanetsRequest{} }
func (m *ListPlanetsRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListPlanetsRequest) ProtoMessage()               {}
func (*ListPlanetsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

type ListPlanetsResponse struct {
	Planets []*Planet `protobuf:"bytes,1,rep,name=planets" json:"planets,omitempty"`
}

func (m *ListPlanetsResponse) Reset()                    { *m = ListPlanetsResponse{} }
func (m *ListPlanetsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListPlanetsResponse) ProtoMessage()               {}
func (*ListPlanetsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *ListPlanetsResponse) GetPlanets() []*Planet {
	if m != nil {
		return m.Planets
	}
	return nil
}

type Person struct {
	Name      string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Height    int32    `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Mass      float32  `protobuf:"fixed32,3,opt,name=mass" json:"mass,omitempty"`
	HairColor string   `protobuf:"bytes,4,opt,name=hair_color,json=hairColor" json:"hair_color,omitempty"`
	SkinColor string   `protobuf:"bytes,5,opt,name=skin_color,json=skinColor" json:"skin_color,omitempty"`
	EyeColor  string   `protobuf:"bytes,6,opt,name=eye_color,json=eyeColor" json:"eye_color,omitempty"`
	BirthYear string   `protobuf:"bytes,7,opt,name=birth_year,json=birthYear" json:"birth_year,omitempty"`
	Gender    string   `protobuf:"bytes,8,opt,name=gender" json:"gender,omitempty"`
	Homeworld string   `protobuf:"bytes,9,opt,name=homeworld" json:"homeworld,omitempty"`
	Films     []string `protobuf:"bytes,10,rep,name=films" json:"films,omitempty"`
	Species   []string `protobuf:"bytes,11,rep,name=species" json:"species,omitempty"`
	Vehicles  []string `protobuf:"bytes,12,rep,name=vehicles" json:"vehicles,omitempty"`
	Starships []string `protobuf:"bytes,13,rep,name=starships" json:"starships,omitempty"`
	Id        string   `protobuf:"bytes,14,opt,name=id" json:"id,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto1.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Person) GetMass() float32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

func (m *Person) GetHairColor() string {
	if m != nil {
		return m.HairColor
	}
	return ""
}

func (m *Person) GetSkinColor() string {
	if m != nil {
		return m.SkinColor
	}
	return ""
}

func (m *Person) GetEyeColor() string {
	if m != nil {
		return m.EyeColor
	}
	return ""
}

func (m *Person) GetBirthYear() string {
	if m != nil {
		return m.BirthYear
	}
	return ""
}

func (m *Person) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Person) GetHomeworld() string {
	if m != nil {
		return m.Homeworld
	}
	return ""
}

func (m *Person) GetFilms() []string {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Person) GetSpecies() []string {
	if m != nil {
		return m.Species
	}
	return nil
}

func (m *Person) GetVehicles() []string {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

func (m *Person) GetStarships() []string {
	if m != nil {
		return m.Starships
	}
	return nil
}

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPersonRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetPersonRequest) Reset()                    { *m = GetPersonRequest{} }
func (m *GetPersonRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetPersonRequest) ProtoMessage()               {}
func (*GetPersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *GetPersonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPersonResponse struct {
	Person *Person `protobuf:"bytes,1,opt,name=person" json:"person,omitempty"`
}

func (m *GetPersonResponse) Reset()                    { *m = GetPersonResponse{} }
func (m *GetPersonResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetPersonResponse) ProtoMessage()               {}
func (*GetPersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *GetPersonResponse) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type ListPeopleRequest struct {
}

func (m *ListPeopleRequest) Reset()                    { *m = ListPeopleRequest{} }
func (m *ListPeopleRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListPeopleRequest) ProtoMessage()               {}
func (*ListPeopleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

type ListPeopleResponse struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *ListPeopleResponse) Reset()                    { *m = ListPeopleResponse{} }
func (m *ListPeopleResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListPeopleResponse) ProtoMessage()               {}
func (*ListPeopleResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *ListPeopleResponse) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type ListStarshipActionsRequest struct {
}

func (m *ListStarshipActionsRequest) Reset()                    { *m = ListStarshipActionsRequest{} }
func (m *ListStarshipActionsRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListStarshipActionsRequest) ProtoMessage()               {}
func (*ListStarshipActionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

type StarshipAction struct {
	Starship *Starship             `protobuf:"bytes,1,opt,name=starship" json:"starship,omitempty"`
	Action   StarshipAction_Action `protobuf:"varint,2,opt,name=action,enum=swapi.v1.StarshipAction_Action" json:"action,omitempty"`
}

func (m *StarshipAction) Reset()                    { *m = StarshipAction{} }
func (m *StarshipAction) String() string            { return proto1.CompactTextString(m) }
func (*StarshipAction) ProtoMessage()               {}
func (*StarshipAction) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *StarshipAction) GetStarship() *Starship {
	if m != nil {
		return m.Starship
	}
	return nil
}

func (m *StarshipAction) GetAction() StarshipAction_Action {
	if m != nil {
		return m.Action
	}
	return StarshipAction_TOOKOFF
}

func init() {
	proto1.RegisterType((*Film)(nil), "swapi.v1.Film")
	proto1.RegisterType((*GetFilmRequest)(nil), "swapi.v1.GetFilmRequest")
	proto1.RegisterType((*GetFilmResponse)(nil), "swapi.v1.GetFilmResponse")
	proto1.RegisterType((*ListFilmsRequest)(nil), "swapi.v1.ListFilmsRequest")
	proto1.RegisterType((*ListFilmsResponse)(nil), "swapi.v1.ListFilmsResponse")
	proto1.RegisterType((*Vehicle)(nil), "swapi.v1.Vehicle")
	proto1.RegisterType((*GetVehicleRequest)(nil), "swapi.v1.GetVehicleRequest")
	proto1.RegisterType((*GetVehicleResponse)(nil), "swapi.v1.GetVehicleResponse")
	proto1.RegisterType((*ListVehiclesRequest)(nil), "swapi.v1.ListVehiclesRequest")
	proto1.RegisterType((*ListVehiclesResponse)(nil), "swapi.v1.ListVehiclesResponse")
	proto1.RegisterType((*Starship)(nil), "swapi.v1.Starship")
	proto1.RegisterType((*GetStarshipRequest)(nil), "swapi.v1.GetStarshipRequest")
	proto1.RegisterType((*GetStarshipResponse)(nil), "swapi.v1.GetStarshipResponse")
	proto1.RegisterType((*ListStarshipsRequest)(nil), "swapi.v1.ListStarshipsRequest")
	proto1.RegisterType((*ListStarshipsResponse)(nil), "swapi.v1.ListStarshipsResponse")
	proto1.RegisterType((*Species)(nil), "swapi.v1.Species")
	proto1.RegisterType((*GetSpeciesRequest)(nil), "swapi.v1.GetSpeciesRequest")
	proto1.RegisterType((*GetSpeciesResponse)(nil), "swapi.v1.GetSpeciesResponse")
	proto1.RegisterType((*ListSpeciesRequest)(nil), "swapi.v1.ListSpeciesRequest")
	proto1.RegisterType((*ListSpeciesResponse)(nil), "swapi.v1.ListSpeciesResponse")
	proto1.RegisterType((*Planet)(nil), "swapi.v1.Planet")
	proto1.RegisterType((*GetPlanetRequest)(nil), "swapi.v1.GetPlanetRequest")
	proto1.RegisterType((*GetPlanetResponse)(nil), "swapi.v1.GetPlanetResponse")
	proto1.RegisterType((*ListPlanetsRequest)(nil), "swapi.v1.ListPlanetsRequest")
	proto1.RegisterType((*ListPlanetsResponse)(nil), "swapi.v1.ListPlanetsResponse")
	proto1.RegisterType((*Person)(nil), "swapi.v1.Person")
	proto1.RegisterType((*GetPersonRequest)(nil), "swapi.v1.GetPersonRequest")
	proto1.RegisterType((*GetPersonResponse)(nil), "swapi.v1.GetPersonResponse")
	proto1.RegisterType((*ListPeopleRequest)(nil), "swapi.v1.ListPeopleRequest")
	proto1.RegisterType((*ListPeopleResponse)(nil), "swapi.v1.ListPeopleResponse")
	proto1.RegisterType((*ListStarshipActionsRequest)(nil), "swapi.v1.ListStarshipActionsRequest")
	proto1.RegisterType((*StarshipAction)(nil), "swapi.v1.StarshipAction")
	proto1.RegisterEnum("swapi.v1.StarshipAction_Action", StarshipAction_Action_name, StarshipAction_Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Starwars service

type StarwarsClient interface {
	GetFilm(ctx context.Context, in *GetFilmRequest, opts ...grpc.CallOption) (*GetFilmResponse, error)
	ListFilms(ctx context.Context, in *ListFilmsRequest, opts ...grpc.CallOption) (*ListFilmsResponse, error)
	GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*GetVehicleResponse, error)
	ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (*ListVehiclesResponse, error)
	GetStarship(ctx context.Context, in *GetStarshipRequest, opts ...grpc.CallOption) (*GetStarshipResponse, error)
	ListStarships(ctx context.Context, in *ListStarshipsRequest, opts ...grpc.CallOption) (*ListStarshipsResponse, error)
	GetSpecies(ctx context.Context, in *GetSpeciesRequest, opts ...grpc.CallOption) (*GetSpeciesResponse, error)
	ListSpecies(ctx context.Context, in *ListSpeciesRequest, opts ...grpc.CallOption) (*ListSpeciesResponse, error)
	GetPlanet(ctx context.Context, in *GetPlanetRequest, opts ...grpc.CallOption) (*GetPlanetResponse, error)
	ListPlanets(ctx context.Context, in *ListPlanetsRequest, opts ...grpc.CallOption) (*ListPlanetsResponse, error)
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
	ListPeople(ctx context.Context, in *ListPeopleRequest, opts ...grpc.CallOption) (*ListPeopleResponse, error)
	ListStarshipActions(ctx context.Context, in *ListStarshipActionsRequest, opts ...grpc.CallOption) (Starwars_ListStarshipActionsClient, error)
}

type starwarsClient struct {
	cc *grpc.ClientConn
}

func NewStarwarsClient(cc *grpc.ClientConn) StarwarsClient {
	return &starwarsClient{cc}
}

func (c *starwarsClient) GetFilm(ctx context.Context, in *GetFilmRequest, opts ...grpc.CallOption) (*GetFilmResponse, error) {
	out := new(GetFilmResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/GetFilm", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) ListFilms(ctx context.Context, in *ListFilmsRequest, opts ...grpc.CallOption) (*ListFilmsResponse, error) {
	out := new(ListFilmsResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/ListFilms", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*GetVehicleResponse, error) {
	out := new(GetVehicleResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/GetVehicle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (*ListVehiclesResponse, error) {
	out := new(ListVehiclesResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/ListVehicles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) GetStarship(ctx context.Context, in *GetStarshipRequest, opts ...grpc.CallOption) (*GetStarshipResponse, error) {
	out := new(GetStarshipResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/GetStarship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) ListStarships(ctx context.Context, in *ListStarshipsRequest, opts ...grpc.CallOption) (*ListStarshipsResponse, error) {
	out := new(ListStarshipsResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/ListStarships", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) GetSpecies(ctx context.Context, in *GetSpeciesRequest, opts ...grpc.CallOption) (*GetSpeciesResponse, error) {
	out := new(GetSpeciesResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/GetSpecies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) ListSpecies(ctx context.Context, in *ListSpeciesRequest, opts ...grpc.CallOption) (*ListSpeciesResponse, error) {
	out := new(ListSpeciesResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/ListSpecies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) GetPlanet(ctx context.Context, in *GetPlanetRequest, opts ...grpc.CallOption) (*GetPlanetResponse, error) {
	out := new(GetPlanetResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/GetPlanet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) ListPlanets(ctx context.Context, in *ListPlanetsRequest, opts ...grpc.CallOption) (*ListPlanetsResponse, error) {
	out := new(ListPlanetsResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/ListPlanets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) ListPeople(ctx context.Context, in *ListPeopleRequest, opts ...grpc.CallOption) (*ListPeopleResponse, error) {
	out := new(ListPeopleResponse)
	err := grpc.Invoke(ctx, "/swapi.v1.Starwars/ListPeople", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsClient) ListStarshipActions(ctx context.Context, in *ListStarshipActionsRequest, opts ...grpc.CallOption) (Starwars_ListStarshipActionsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Starwars_serviceDesc.Streams[0], c.cc, "/swapi.v1.Starwars/ListStarshipActions", opts...)
	if err != nil {
		return nil, err
	}
	x := &starwarsListStarshipActionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Starwars_ListStarshipActionsClient interface {
	Recv() (*StarshipAction, error)
	grpc.ClientStream
}

type starwarsListStarshipActionsClient struct {
	grpc.ClientStream
}

func (x *starwarsListStarshipActionsClient) Recv() (*StarshipAction, error) {
	m := new(StarshipAction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Starwars service

type StarwarsServer interface {
	GetFilm(context.Context, *GetFilmRequest) (*GetFilmResponse, error)
	ListFilms(context.Context, *ListFilmsRequest) (*ListFilmsResponse, error)
	GetVehicle(context.Context, *GetVehicleRequest) (*GetVehicleResponse, error)
	ListVehicles(context.Context, *ListVehiclesRequest) (*ListVehiclesResponse, error)
	GetStarship(context.Context, *GetStarshipRequest) (*GetStarshipResponse, error)
	ListStarships(context.Context, *ListStarshipsRequest) (*ListStarshipsResponse, error)
	GetSpecies(context.Context, *GetSpeciesRequest) (*GetSpeciesResponse, error)
	ListSpecies(context.Context, *ListSpeciesRequest) (*ListSpeciesResponse, error)
	GetPlanet(context.Context, *GetPlanetRequest) (*GetPlanetResponse, error)
	ListPlanets(context.Context, *ListPlanetsRequest) (*ListPlanetsResponse, error)
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
	ListPeople(context.Context, *ListPeopleRequest) (*ListPeopleResponse, error)
	ListStarshipActions(*ListStarshipActionsRequest, Starwars_ListStarshipActionsServer) error
}

func RegisterStarwarsServer(s *grpc.Server, srv StarwarsServer) {
	s.RegisterService(&_Starwars_serviceDesc, srv)
}

func _Starwars_GetFilm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).GetFilm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/GetFilm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).GetFilm(ctx, req.(*GetFilmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_ListFilms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).ListFilms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/ListFilms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).ListFilms(ctx, req.(*ListFilmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_GetVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).GetVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/GetVehicle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).GetVehicle(ctx, req.(*GetVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_ListVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).ListVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/ListVehicles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).ListVehicles(ctx, req.(*ListVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_GetStarship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStarshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).GetStarship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/GetStarship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).GetStarship(ctx, req.(*GetStarshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_ListStarships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStarshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).ListStarships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/ListStarships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).ListStarships(ctx, req.(*ListStarshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_GetSpecies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpeciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).GetSpecies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/GetSpecies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).GetSpecies(ctx, req.(*GetSpeciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_ListSpecies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpeciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).ListSpecies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/ListSpecies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).ListSpecies(ctx, req.(*ListSpeciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_GetPlanet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).GetPlanet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/GetPlanet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).GetPlanet(ctx, req.(*GetPlanetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_ListPlanets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlanetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).ListPlanets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/ListPlanets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).ListPlanets(ctx, req.(*ListPlanetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_ListPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeopleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).ListPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.v1.Starwars/ListPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).ListPeople(ctx, req.(*ListPeopleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Starwars_ListStarshipActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListStarshipActionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StarwarsServer).ListStarshipActions(m, &starwarsListStarshipActionsServer{stream})
}

type Starwars_ListStarshipActionsServer interface {
	Send(*StarshipAction) error
	grpc.ServerStream
}

type starwarsListStarshipActionsServer struct {
	grpc.ServerStream
}

func (x *starwarsListStarshipActionsServer) Send(m *StarshipAction) error {
	return x.ServerStream.SendMsg(m)
}

var _Starwars_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swapi.v1.Starwars",
	HandlerType: (*StarwarsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilm",
			Handler:    _Starwars_GetFilm_Handler,
		},
		{
			MethodName: "ListFilms",
			Handler:    _Starwars_ListFilms_Handler,
		},
		{
			MethodName: "GetVehicle",
			Handler:    _Starwars_GetVehicle_Handler,
		},
		{
			MethodName: "ListVehicles",
			Handler:    _Starwars_ListVehicles_Handler,
		},
		{
			MethodName: "GetStarship",
			Handler:    _Starwars_GetStarship_Handler,
		},
		{
			MethodName: "ListStarships",
			Handler:    _Starwars_ListStarships_Handler,
		},
		{
			MethodName: "GetSpecies",
			Handler:    _Starwars_GetSpecies_Handler,
		},
		{
			MethodName: "ListSpecies",
			Handler:    _Starwars_ListSpecies_Handler,
		},
		{
			MethodName: "GetPlanet",
			Handler:    _Starwars_GetPlanet_Handler,
		},
		{
			MethodName: "ListPlanets",
			Handler:    _Starwars_ListPlanets_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _Starwars_GetPerson_Handler,
		},
		{
			MethodName: "ListPeople",
			Handler:    _Starwars_ListPeople_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStarshipActions",
			Handler:       _Starwars_ListStarshipActions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swapi.proto",
}

func init() { proto1.RegisterFile("swapi.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1812 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x98, 0xdd, 0x72, 0x1b, 0x49,
	0x15, 0xc7, 0xd7, 0x52, 0x2c, 0x69, 0x8e, 0x6c, 0x59, 0x6e, 0x7f, 0x64, 0x22, 0xdb, 0x89, 0x99,
	0x0d, 0x4b, 0x60, 0x0b, 0x7b, 0x37, 0x40, 0x51, 0x5c, 0x40, 0x95, 0xd7, 0x76, 0x62, 0x17, 0x21,
	0x71, 0x29, 0xcb, 0x52, 0xa1, 0xa0, 0x54, 0x9d, 0x99, 0xb6, 0xd4, 0xc5, 0x68, 0x66, 0xe8, 0x19,
	0xd9, 0xeb, 0xa2, 0xb8, 0xe1, 0x11, 0xe0, 0x39, 0x78, 0x00, 0xae, 0x79, 0x04, 0xae, 0xb8, 0xe2,
	0x86, 0x17, 0x80, 0x27, 0xa0, 0xfa, 0xf4, 0xe9, 0xf9, 0x92, 0x94, 0x84, 0x9b, 0xbd, 0xb2, 0xfa,
	0x7f, 0xce, 0xf4, 0xe9, 0x9e, 0xfe, 0xf5, 0x39, 0x67, 0x0c, 0xdd, 0xf4, 0x96, 0x27, 0xf2, 0x28,
	0x51, 0x71, 0x16, 0xb3, 0x8e, 0x19, 0xdc, 0x7c, 0x3e, 0xd8, 0x1f, 0xc7, 0xf1, 0x38, 0x14, 0xc7,
	0x3c, 0x91, 0xc7, 0x3c, 0x8a, 0xe2, 0x8c, 0x67, 0x32, 0x8e, 0x52, 0xe3, 0x37, 0xd8, 0x23, 0x2b,
	0x8e, 0xde, 0xce, 0xae, 0x8f, 0xc5, 0x34, 0xc9, 0xee, 0x8c, 0xd1, 0xfb, 0x67, 0x03, 0xee, 0x3d,
	0x93, 0xe1, 0x94, 0x6d, 0xc3, 0x6a, 0x26, 0xb3, 0x50, 0xb8, 0x2b, 0x87, 0x2b, 0x4f, 0x9c, 0xa1,
	0x19, 0xb0, 0x03, 0x00, 0x91, 0xc8, 0x34, 0x0e, 0xc4, 0x48, 0x06, 0x6e, 0xe3, 0x70, 0xe5, 0xc9,
	0xea, 0xd0, 0x21, 0xe5, 0x32, 0x60, 0x1f, 0xc3, 0x7a, 0x9c, 0x88, 0x48, 0x46, 0xe3, 0x91, 0xaf,
	0xf8, 0x6d, 0xe8, 0x36, 0xf1, 0xe1, 0x35, 0x12, 0x4f, 0xb5, 0xc6, 0x06, 0xd0, 0x09, 0xa4, 0x12,
	0x7e, 0x16, 0x2b, 0xf7, 0x1e, 0xda, 0xf3, 0xb1, 0xb6, 0x25, 0x2a, 0x0e, 0x66, 0xbe, 0x50, 0xee,
	0xaa, 0xb1, 0xd9, 0x31, 0xfb, 0x16, 0xac, 0x29, 0x11, 0x0a, 0x9e, 0x8a, 0x51, 0xc0, 0x33, 0xe1,
	0xb6, 0xd0, 0xde, 0x25, 0xed, 0x8c, 0x67, 0x82, 0x3d, 0x04, 0xf0, 0x27, 0x5c, 0x71, 0x3f, 0x13,
	0x2a, 0x75, 0xdb, 0x87, 0xcd, 0x27, 0xce, 0xb0, 0xa4, 0x30, 0x17, 0xda, 0x49, 0xc8, 0x23, 0x91,
	0xa5, 0x6e, 0x07, 0x8d, 0x76, 0xc8, 0xf6, 0xc1, 0x49, 0x33, 0xae, 0xd2, 0x89, 0x4c, 0x52, 0xd7,
	0x41, 0x5b, 0x21, 0xe8, 0x65, 0xdd, 0x88, 0x89, 0xf4, 0x43, 0x91, 0xba, 0x80, 0xc6, 0x7c, 0xac,
	0xe7, 0x4c, 0x13, 0xe1, 0x4b, 0x91, 0xba, 0x5d, 0x33, 0x27, 0x0d, 0x59, 0x0f, 0x1a, 0x32, 0x70,
	0xd7, 0x70, 0x99, 0x0d, 0x19, 0x78, 0x87, 0xd0, 0x7b, 0x2e, 0x32, 0xfd, 0x76, 0x87, 0xe2, 0xf7,
	0x33, 0x91, 0x66, 0xe4, 0xb1, 0x92, 0x7b, 0xfc, 0x08, 0x36, 0x72, 0x8f, 0x34, 0x89, 0xa3, 0x54,
	0x30, 0x0f, 0xee, 0x5d, 0xcb, 0x70, 0x8a, 0x4e, 0xdd, 0xa7, 0xbd, 0x23, 0x7b, 0xc8, 0x47, 0xe8,
	0x85, 0x36, 0x8f, 0x41, 0xff, 0x85, 0x4c, 0xf1, 0xb9, 0x94, 0xa6, 0xf6, 0x7e, 0x02, 0x9b, 0x25,
	0x8d, 0x26, 0x7b, 0x0c, 0xab, 0xfa, 0x81, 0xd4, 0x5d, 0x39, 0x6c, 0x2e, 0x98, 0xcd, 0x18, 0xbd,
	0xbf, 0x36, 0xa1, 0xfd, 0x95, 0xd9, 0x1e, 0x63, 0x70, 0x2f, 0xe2, 0x53, 0x4b, 0x01, 0xfe, 0xd6,
	0x68, 0x4c, 0xe3, 0x40, 0x84, 0x78, 0xfe, 0xce, 0xd0, 0x0c, 0x98, 0x07, 0x6b, 0x53, 0x1e, 0xcd,
	0xae, 0xb9, 0x9f, 0xcd, 0x94, 0x50, 0xf6, 0xe8, 0xcb, 0x1a, 0xfb, 0x04, 0x36, 0xfc, 0x38, 0xcd,
	0x46, 0x32, 0x1a, 0xf9, 0x4a, 0x04, 0x32, 0x4b, 0x91, 0x80, 0xd5, 0xe1, 0xba, 0x96, 0x2f, 0xa3,
	0x53, 0x23, 0xb2, 0x5d, 0x68, 0x85, 0x22, 0x1a, 0x67, 0x13, 0x84, 0xa0, 0x31, 0xa4, 0x11, 0xfb,
	0x21, 0xec, 0x4e, 0xf9, 0xd7, 0x23, 0x9e, 0x4d, 0xe3, 0x34, 0x99, 0x08, 0xa5, 0x41, 0x4b, 0x13,
	0x21, 0x02, 0x84, 0x61, 0x75, 0xb8, 0x3d, 0xe5, 0x5f, 0x9f, 0x94, 0x8c, 0xaf, 0xb5, 0x4d, 0xef,
	0xc1, 0x57, 0xe2, 0xd6, 0x6d, 0xa3, 0x0f, 0xfe, 0xd6, 0xa4, 0x24, 0x3c, 0x4d, 0x45, 0x34, 0xd6,
	0xa4, 0x74, 0xd0, 0x52, 0x52, 0xd8, 0xb7, 0xa1, 0xe7, 0x73, 0x35, 0x8e, 0x47, 0x3e, 0x4f, 0xb8,
	0x2f, 0xb3, 0x3b, 0xd7, 0xa1, 0x85, 0x6a, 0xf5, 0x94, 0x44, 0x76, 0x08, 0x5d, 0x3f, 0x8e, 0xd2,
	0xd9, 0x94, 0xbf, 0x35, 0x6c, 0x20, 0x92, 0x25, 0x49, 0x5f, 0x09, 0x42, 0x65, 0xe4, 0x87, 0x3c,
	0xd5, 0x90, 0xe0, 0x7b, 0x21, 0xf1, 0x54, 0x6b, 0x7a, 0xbf, 0x89, 0x0c, 0xe3, 0x2c, 0x75, 0xd7,
	0x10, 0x21, 0x1a, 0xe9, 0x37, 0x6d, 0xce, 0x6b, 0x1d, 0x65, 0x33, 0x20, 0x6a, 0x7a, 0x39, 0x35,
	0x1f, 0xc3, 0xe6, 0x73, 0x91, 0xd1, 0x89, 0x2d, 0x43, 0xeb, 0x04, 0x58, 0xd9, 0x89, 0x80, 0xf8,
	0x14, 0xda, 0xb4, 0x10, 0x02, 0x6c, 0xb3, 0x40, 0xc2, 0xfa, 0x5a, 0x0f, 0x6f, 0x07, 0xb6, 0x34,
	0x52, 0xa4, 0xe7, 0xa4, 0x9d, 0xc3, 0x76, 0x55, 0xa6, 0xb9, 0xbf, 0x5f, 0xba, 0x34, 0x86, 0xb7,
	0x05, 0x93, 0xe7, 0x2e, 0xde, 0x7f, 0x9a, 0xd0, 0x79, 0x4d, 0x37, 0xee, 0x9b, 0xc1, 0xae, 0xf9,
	0xa1, 0xd8, 0x59, 0x80, 0x5a, 0x4b, 0x01, 0x6a, 0x7f, 0x00, 0x40, 0x1d, 0x0a, 0xf9, 0x2e, 0x80,
	0x9c, 0x79, 0x80, 0x3e, 0x85, 0xcd, 0xc9, 0x5d, 0x22, 0x54, 0xa0, 0xe4, 0x8d, 0x18, 0x29, 0x9e,
	0xc9, 0x68, 0x8c, 0xa0, 0x35, 0x86, 0xfd, 0xc2, 0x30, 0x44, 0x5d, 0xaf, 0x74, 0x3a, 0x0e, 0x33,
	0x84, 0x6c, 0x75, 0x88, 0xbf, 0xf5, 0x4a, 0x6c, 0x26, 0x23, 0x04, 0x4d, 0x4a, 0x5a, 0xb7, 0x6a,
	0x9d, 0xc1, 0xf5, 0xc5, 0x0c, 0xf6, 0xe6, 0x19, 0xdc, 0xb0, 0x78, 0xbd, 0xe3, 0x66, 0xf6, 0x71,
	0xdb, 0x0b, 0x6f, 0xa6, 0xf7, 0x18, 0xa1, 0xb4, 0xa7, 0xbe, 0x0c, 0xdd, 0x73, 0xd8, 0xaa, 0x78,
	0x11, 0x5f, 0x47, 0xd0, 0xb1, 0x3b, 0x20, 0x78, 0x59, 0xc1, 0x57, 0xee, 0x9d, 0xfb, 0x78, 0xbb,
	0x86, 0x53, 0x6b, 0xc9, 0xf9, 0xbd, 0x84, 0x9d, 0x9a, 0x4e, 0x01, 0x3e, 0x2b, 0xd7, 0x04, 0x43,
	0xf0, 0xa2, 0x08, 0x85, 0x93, 0xf7, 0xe7, 0x26, 0xb4, 0x5f, 0x53, 0xf6, 0x5f, 0x84, 0xf0, 0x27,
	0xd0, 0xc3, 0x13, 0x90, 0xd7, 0xd2, 0xc7, 0x9a, 0x4c, 0x2c, 0xd7, 0x54, 0x4d, 0x45, 0x20, 0x52,
	0x39, 0x8e, 0x8c, 0x93, 0x61, 0xba, 0x2c, 0xe9, 0x43, 0xe5, 0x37, 0x42, 0xf1, 0xb1, 0x18, 0x4d,
	0x84, 0x1c, 0x4f, 0x32, 0x9b, 0x48, 0x49, 0xbd, 0x40, 0x91, 0x3d, 0x82, 0x6e, 0xfa, 0x3b, 0x8d,
	0x7d, 0x1c, 0xc6, 0x2a, 0xa5, 0x92, 0x0a, 0x5a, 0x3a, 0x45, 0x05, 0x0b, 0xfa, 0x9d, 0xb0, 0x76,
	0x53, 0x52, 0x1d, 0x71, 0x27, 0xc8, 0xfc, 0x5d, 0xe8, 0xdb, 0x30, 0xa1, 0xbc, 0x16, 0x69, 0xc2,
	0x23, 0x62, 0x7d, 0x83, 0xf4, 0x17, 0x24, 0xeb, 0x0a, 0x3a, 0x89, 0xa7, 0xe2, 0x36, 0x56, 0x61,
	0x80, 0xac, 0x3b, 0xc3, 0x42, 0xd0, 0x15, 0x34, 0xe4, 0xd1, 0x78, 0xc6, 0xc7, 0x82, 0x20, 0xcf,
	0xc7, 0x48, 0x9e, 0x88, 0x93, 0x50, 0x50, 0x6d, 0xa5, 0x51, 0x41, 0x5e, 0x77, 0x9e, 0xbc, 0xbc,
	0xaa, 0xea, 0x2d, 0x4e, 0xb8, 0x54, 0x76, 0x0b, 0xeb, 0x66, 0x8b, 0x5a, 0x32, 0x7b, 0xa0, 0xf4,
	0x48, 0xc7, 0xf2, 0xee, 0xf4, 0x98, 0x3b, 0x15, 0xe9, 0xd1, 0xd6, 0xf6, 0xb9, 0xf4, 0x68, 0x7d,
	0xad, 0x87, 0xb7, 0x0d, 0x0c, 0x39, 0xaa, 0x04, 0xf2, 0xbe, 0x30, 0x49, 0xf3, 0x9d, 0x33, 0x37,
	0xdf, 0x33, 0xf3, 0xbf, 0x1a, 0xd0, 0xba, 0xc2, 0x46, 0x65, 0x21, 0x55, 0xdf, 0x81, 0x0d, 0x45,
	0x3d, 0xde, 0x28, 0x11, 0x4a, 0xc6, 0xb6, 0x33, 0xeb, 0x59, 0xf9, 0x0a, 0x55, 0x0d, 0x4d, 0xac,
	0xde, 0xca, 0x8c, 0x87, 0xd6, 0xaf, 0x69, 0xa0, 0x21, 0x95, 0xdc, 0xb0, 0x41, 0xe3, 0x53, 0x91,
	0x09, 0x45, 0x54, 0xe5, 0x63, 0xdd, 0xed, 0xf8, 0xa1, 0x9c, 0xea, 0xfe, 0xcb, 0xc0, 0x64, 0x87,
	0xda, 0x32, 0x56, 0xfc, 0x46, 0x67, 0xba, 0x16, 0x66, 0x27, 0x3b, 0xd4, 0x96, 0x4c, 0x28, 0xc5,
	0xa5, 0x61, 0xc7, 0x19, 0xda, 0xa1, 0x2e, 0x8e, 0xe9, 0x4c, 0x5d, 0x73, 0x5f, 0x8c, 0x6e, 0xb9,
	0x0e, 0xd7, 0xc1, 0x27, 0xd7, 0x48, 0xfc, 0x95, 0xd6, 0x30, 0xd3, 0xc6, 0xc9, 0x2c, 0x34, 0x77,
	0xc1, 0xc1, 0x74, 0x52, 0x52, 0x34, 0x78, 0x4a, 0xa4, 0x32, 0x10, 0x51, 0x66, 0xbb, 0xb3, 0x42,
	0xf8, 0x30, 0x88, 0x3c, 0x0f, 0xfa, 0xcf, 0x45, 0x66, 0xde, 0xf1, 0x32, 0x44, 0x7e, 0x8a, 0x1c,
	0x59, 0x1f, 0x3a, 0xc7, 0x27, 0xd0, 0x32, 0x2d, 0x24, 0x01, 0xd2, 0x2f, 0x8e, 0x91, 0x3c, 0xc9,
	0x6e, 0xf1, 0x30, 0x6a, 0x8e, 0xc7, 0x89, 0xc1, 0x23, 0x57, 0x69, 0xda, 0xef, 0x15, 0x8d, 0xaa,
	0xc1, 0x63, 0x7e, 0x5e, 0xeb, 0xe0, 0xfd, 0x57, 0xd3, 0x21, 0x54, 0x1a, 0x47, 0x0b, 0xe9, 0xd8,
	0x85, 0x16, 0x65, 0x08, 0x03, 0x05, 0x8d, 0xb0, 0x54, 0xe8, 0x62, 0xd0, 0xc4, 0x57, 0x8e, 0xbf,
	0x75, 0x36, 0x28, 0xee, 0x12, 0x35, 0xe7, 0x4e, 0x7e, 0x95, 0xb4, 0xb9, 0xc8, 0x26, 0x74, 0xfe,
	0x4e, 0x9e, 0x4c, 0xd8, 0x1e, 0x38, 0x79, 0x2e, 0xa1, 0x54, 0xd2, 0xb1, 0xa9, 0x44, 0x3f, 0xfb,
	0x56, 0xaa, 0x6c, 0x32, 0xba, 0x13, 0x5c, 0x11, 0x07, 0x0e, 0x2a, 0x6f, 0x04, 0x57, 0x7a, 0x95,
	0x63, 0x11, 0x05, 0x84, 0x80, 0x33, 0xa4, 0x51, 0x35, 0xab, 0x38, 0xf5, 0xac, 0x92, 0x1f, 0x2e,
	0x94, 0x0f, 0x77, 0x79, 0x47, 0x5e, 0xee, 0xe3, 0xd7, 0x6a, 0x7d, 0x7c, 0xe5, 0x0b, 0x60, 0xbd,
	0xfe, 0x05, 0x50, 0xef, 0xb9, 0x08, 0x18, 0x7c, 0xed, 0xef, 0x01, 0x86, 0x7c, 0x4a, 0xc0, 0xa0,
	0xb2, 0x00, 0x18, 0xe3, 0x49, 0x76, 0x6f, 0xcb, 0x74, 0xf0, 0x57, 0x98, 0x0c, 0x2d, 0x2f, 0x3f,
	0x23, 0x8a, 0x48, 0x2c, 0x4f, 0x8a, 0x19, 0x74, 0x9e, 0x96, 0x7c, 0x52, 0x6d, 0xf7, 0xf6, 0x61,
	0x50, 0x2e, 0x76, 0x27, 0x3e, 0x7e, 0x19, 0xda, 0xd9, 0xff, 0xbe, 0x02, 0xbd, 0xaa, 0xe9, 0xff,
	0xad, 0xb2, 0xec, 0xc7, 0xd0, 0xe2, 0x7e, 0x5e, 0xda, 0x7a, 0x4f, 0x1f, 0xcd, 0x7b, 0x9b, 0x99,
	0x8f, 0xcc, 0x9f, 0x21, 0xb9, 0x7b, 0x17, 0xd0, 0xa2, 0x90, 0x5d, 0x68, 0x7f, 0xf9, 0xea, 0xd5,
	0xcf, 0x5f, 0x3d, 0x7b, 0xd6, 0xff, 0x88, 0x01, 0xb4, 0x5e, 0x9c, 0xbc, 0x3c, 0x3b, 0x3f, 0xeb,
	0xaf, 0xb0, 0x1e, 0xc0, 0xc5, 0x9b, 0xab, 0xf3, 0xe1, 0xd9, 0xf0, 0xf2, 0xab, 0xf3, 0x7e, 0x83,
	0xed, 0xc0, 0xe6, 0xc5, 0xe5, 0xd9, 0xe5, 0xcb, 0xe7, 0xa3, 0xcb, 0x97, 0xa3, 0x93, 0xd1, 0x2f,
	0x5e, 0xfd, 0xf2, 0xcb, 0x8b, 0x7e, 0xf3, 0xe9, 0xdf, 0xc0, 0x74, 0x92, 0xb7, 0x5c, 0xa5, 0xec,
	0x37, 0xd0, 0xa6, 0x4f, 0x2a, 0xe6, 0x16, 0x4b, 0xa9, 0x7e, 0x87, 0x0d, 0x1e, 0x2c, 0xb0, 0x98,
	0x57, 0xeb, 0xed, 0xff, 0xe9, 0x1f, 0xff, 0xfe, 0x4b, 0x63, 0x97, 0x6d, 0x1f, 0xa3, 0xcb, 0xf1,
	0xcd, 0xe7, 0xc7, 0x48, 0xd9, 0xf1, 0x1f, 0x64, 0xf0, 0x47, 0xf6, 0x5b, 0x70, 0xf2, 0xaf, 0x2c,
	0x36, 0x28, 0x66, 0xa9, 0x7f, 0x8e, 0x0d, 0xf6, 0x16, 0xda, 0x28, 0xc6, 0x7d, 0x8c, 0xb1, 0xc9,
	0x36, 0x6a, 0x31, 0xd8, 0x04, 0xa0, 0x68, 0xda, 0xd9, 0x5e, 0x65, 0x95, 0xd5, 0x7e, 0x7f, 0xb0,
	0xbf, 0xd8, 0x48, 0x11, 0x1e, 0x61, 0x84, 0x07, 0xec, 0x7e, 0x11, 0xc1, 0x82, 0x6f, 0x36, 0x22,
	0x61, 0xad, 0xdc, 0xc4, 0xb3, 0x83, 0xea, 0x7a, 0x6b, 0x3d, 0xff, 0xe0, 0xe1, 0x32, 0x33, 0xc5,
	0x1b, 0x60, 0xbc, 0x6d, 0xc6, 0xe6, 0xe3, 0xb1, 0x10, 0xba, 0xa5, 0x76, 0x8e, 0x55, 0x17, 0x5e,
	0xeb, 0x05, 0x07, 0x07, 0x4b, 0xac, 0x14, 0xe7, 0x10, 0xe3, 0x0c, 0x98, 0x5b, 0xc4, 0xc9, 0xef,
	0xac, 0xd9, 0xd8, 0x14, 0xd6, 0x2b, 0xdd, 0x1d, 0xab, 0x2d, 0xbd, 0xde, 0x0e, 0x0e, 0x1e, 0x2d,
	0xb5, 0x53, 0xcc, 0x3d, 0x8c, 0xb9, 0xc3, 0xb6, 0x16, 0xc4, 0x64, 0x63, 0x3c, 0x31, 0xdb, 0x03,
	0x56, 0x4f, 0xac, 0xda, 0x19, 0xd4, 0x4e, 0xac, 0xd6, 0x20, 0x78, 0x0f, 0x31, 0x8a, 0xcb, 0x76,
	0x4b, 0x51, 0x8c, 0x8b, 0xd9, 0x97, 0x80, 0x6e, 0xa9, 0xaf, 0x28, 0xbf, 0xc5, 0xf9, 0x26, 0x64,
	0x70, 0xb0, 0xc4, 0x4a, 0xb1, 0x1e, 0x60, 0xac, 0x2d, 0xb6, 0x39, 0x17, 0x8b, 0x05, 0xe0, 0xe4,
	0x45, 0xaf, 0x0c, 0x78, 0xbd, 0x5a, 0x0e, 0xf6, 0x16, 0xda, 0x96, 0x6f, 0x86, 0xaa, 0x57, 0x65,
	0x33, 0x57, 0xf6, 0x9f, 0x31, 0xd5, 0xe5, 0x56, 0x4b, 0x66, 0x7d, 0x33, 0xb5, 0xd2, 0xb9, 0x68,
	0x33, 0xf6, 0x9f, 0x3c, 0xbe, 0xd9, 0x8c, 0xa9, 0x95, 0xb5, 0xcd, 0x94, 0x33, 0x79, 0x7d, 0x33,
	0x95, 0x0c, 0xee, 0x1d, 0x60, 0x80, 0xfb, 0x6c, 0xa7, 0x14, 0x00, 0x93, 0xab, 0xd9, 0x0b, 0x07,
	0x28, 0x32, 0x34, 0xab, 0xdd, 0xfb, 0x4a, 0x32, 0x1f, 0xec, 0x2f, 0x36, 0x52, 0x1c, 0x17, 0xe3,
	0x30, 0xd6, 0xaf, 0xc7, 0x61, 0x6f, 0xa8, 0xa7, 0xac, 0x26, 0x71, 0xf6, 0x78, 0x31, 0xb9, 0xd5,
	0x1c, 0x3f, 0x70, 0x97, 0x25, 0x64, 0xef, 0xa3, 0xcf, 0x56, 0xbe, 0x68, 0xff, 0x7a, 0xd5, 0xfc,
	0x5f, 0xb0, 0x85, 0x7f, 0x7e, 0xf0, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x10, 0x6d, 0x89,
	0x63, 0x14, 0x00, 0x00,
}
