# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/thing.proto for package 'practical.grpc.v1'

require 'grpc'
require 'proto/thing_pb'

module Practical
  module Grpc
    module V1
      module MyService
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'practical.grpc.v1.MyService'

          rpc :UpdateThing, UpdateThingRequest, UpdateThingResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
