# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/thing.proto

require 'google/protobuf'

require 'google/protobuf/field_mask_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "practical.grpc.v1.Thing" do
    optional :id, :int64, 1
    optional :name, :string, 2
    optional :cool, :bool, 3
  end
  add_message "practical.grpc.v1.ThingNotFoundError" do
    optional :requested_id, :int64, 1
    optional :reason, :string, 2
  end
  add_message "practical.grpc.v1.UpdateThingRequest" do
    optional :thing, :message, 1, "practical.grpc.v1.Thing"
    optional :mask, :message, 2, "google.protobuf.FieldMask"
  end
  add_message "practical.grpc.v1.UpdateThingResponse" do
    optional :thing, :message, 1, "practical.grpc.v1.Thing"
  end
end

module Practical
  module Grpc
    module V1
      Thing = Google::Protobuf::DescriptorPool.generated_pool.lookup("practical.grpc.v1.Thing").msgclass
      ThingNotFoundError = Google::Protobuf::DescriptorPool.generated_pool.lookup("practical.grpc.v1.ThingNotFoundError").msgclass
      UpdateThingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("practical.grpc.v1.UpdateThingRequest").msgclass
      UpdateThingResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("practical.grpc.v1.UpdateThingResponse").msgclass
    end
  end
end
